import{a as L,S,i as l}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const q="44745838-36a359f27047326ac7e1bdda5",$="https://pixabay.com/api/",E=15;async function f(e,r=1){const s=`${$}?key=${q}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${E}`;try{return(await L.get(s)).data}catch(n){console.log(n)}}let d;function y(e){const r=document.querySelector("#gallery");r.innerHTML=e.map(({largeImageURL:s,webformatURL:n,tags:t,likes:o,views:i,comments:h,downloads:b})=>`
      <a href="${s}" class="gallery-item">
        <img src="${n}" alt="${t}" loading="lazy" />
        <div class="info">
          <p><b>Likes</b>: ${o}</p>
          <p><b>Views</b>: ${i}</p>
          <p><b>Comments</b>: ${h}</p>
          <p><b>Downloads</b>: ${b}</p>
        </div>
      </a>
    `).join(""),d?d.refresh():d=new S(".gallery-item",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function P(){const e=document.querySelector("#gallery");e.innerHTML=""}function c(e){document.querySelector("#loader").classList.toggle("hidden",!e)}function u(e){document.querySelector("#load-more").classList.toggle("hidden",!e)}let a=1,g="";const m=document.querySelector(".js-form"),w=document.querySelector("#load-more");m.addEventListener("submit",v);async function v(e){e.preventDefault();const r=e.currentTarget.elements.query.value.trim();if(!r){l.error({title:"Error",message:"❌ Please enter a search query"});return}g=r,a=1,P(),c(!0),u(!1);try{const s=await f(r,a);s.hits.length===0?l.warning({title:"No Results",message:"Sorry, there are no images matching your search query."}):(y(s.hits),s.totalHits>a*15&&u(!0))}catch(s){p(s)}finally{c(!1),m.reset()}}w.addEventListener("click",B);async function B(){a+=1,c(!0),u(!1);try{const e=await f(g,a);y(e.hits),a*15>=e.totalHits?l.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}):u(!0),M()}catch(e){p(e)}finally{c(!1)}}function p(e){l.error({title:"Error",message:`❌ No pictures found. Error: ${e.message}`})}function M(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
