import{a as S,i,S as q}from"./assets/vendor-b0d10f48.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const L="44745838-36a359f27047326ac7e1bdda5",E="https://pixabay.com/api/",$=15;async function y(e,o=1){const s=`${E}?key=${L}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${$}`;try{return(await S.get(s)).data}catch{i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}}let d;function f(e){document.querySelector("#gallery").insertAdjacentHTML("beforeend",e.map(({largeImageURL:s,webformatURL:a,tags:t,likes:r,views:l,comments:p,downloads:b})=>`
      <a href="${s}" class="gallery-item">
        <img src="${a}" alt="${t}" loading="lazy" />
        <div class="info">
          <p><b>Likes</b>: ${r}</p>
          <p><b>Views</b>: ${l}</p>
          <p><b>Comments</b>: ${p}</p>
          <p><b>Downloads</b>: ${b}</p>
        </div>
      </a>
    `).join("")),d?d.refresh():d=new q(".gallery-item",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function P(){const e=document.querySelector("#gallery");e.innerHTML=""}function c(e){document.querySelector("#loader").classList.toggle("hidden",!e)}function u(e){document.querySelector("#load-more").classList.toggle("hidden",!e)}let n=1,g="";const m=document.querySelector(".js-form"),w=document.querySelector("#load-more");document.querySelector("#loader");document.querySelector("#gallery");m.addEventListener("submit",v);async function v(e){e.preventDefault();const o=e.currentTarget.elements.query.value.trim();if(!o){i.error({title:"Error",message:"❌ Please enter a search query"});return}g=o,n=1,P(),c(!0),u(!1);try{const s=await y(o,n);s.hits.length===0?i.warning({title:"No Results",message:"Sorry, there are no images matching your search query."}):(f(s.hits),s.totalHits>n*15&&u(!0))}catch(s){h(s)}finally{c(!1),m.reset()}}w.addEventListener("click",B);async function B(){n+=1,c(!0),u(!1);try{const e=await y(g,n);f(e.hits),n*15>=e.totalHits?i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}):u(!0),M()}catch(e){h(e)}finally{c(!1)}}function h(e){i.error({title:"Error",message:`❌ No pictures found. Error: ${e.message}`})}function M(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
